name: Refresh Keys

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Refresh keys
        run: |
          GIT_SSH_COMMAND='ssh -i keys/id_rsa -o IdentitiesOnly=yes' git clone git@github.com:nelsonjchen/lan-ssh.git ./temp_clone_rsa
          rm -rf ./temp_clone_rsa
          GIT_SSH_COMMAND='ssh -i keys/id_ed25519 -o IdentitiesOnly=yes' git clone git@github.com:nelsonjchen/lan-ssh.git ./temp_clone_ed25519
          rm -rf ./temp_clone_ed25519
